### ISSUE TITLE
Step 2: vame.rnn_model() UnboundLocalError: local variable 'idx' referenced before assignment

### ISSUE THREAD

**Issue by kubraeryilmaz** [LINCellularNeuroscience/VAME#22]
Hi, 
After executing first step in the guide successfully, I got "UnboundLocalError: local variable 'idx' referenced before assignment" in step 2 (vame.rnn_model() step). Error refers to "VAME/vame/model/rnn_vae.py", line 291. Do you know why I am getting this error and how can i fix it?
```
(vame) [eryilmaz@scc-q28 VAME]$ python3
Python 3.7.7 (default, May 21 2020, 14:57:43) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vame
>>> config='/projectnb/dnn-motion/kubra/VAME/vame_trial_3-Dec2-2020/config.yaml'
>>> vame.rnn_model(config, model_name='VAME', pretrained_weights=False, pretrained_model=None)
Train RNN model!
Using CUDA
GPU active: True
GPU used: Tesla V100-PCIE-16GB
Latent Dimensions: 30, Beta: 1, lr: 0.0005
Initialize train data. Datapoints 160
Initialize test data. Datapoints 40
Epoch: 1
Train: 
/share/pkg.7/pytorch/1.6.0/install/3.7/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:123: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/projectnb2/dnn-motion/kubra/VAME/vame/model/rnn_vae.py", line 444, in rnn_model
    TRAIN_BATCH_SIZE)
  File "/projectnb2/dnn-motion/kubra/VAME/vame/model/rnn_vae.py", line 291, in train
    print('Average Train loss: {:.4f}, MSE-Loss: {:.4f}, MSE-Future-Loss {:.4f}, KL-Loss: {:.4f},  Kmeans-Loss: {:.4f}, weigt: {:.4f}'.format(train_loss / idx,
UnboundLocalError: local variable 'idx' referenced before assignment

```

**Comment by KLuxem** [comment]
Hi,

my initial guess is that somehow your dataloader is empty. Did you run the `vame.create_trainset(config)` function?
Otherwise, can you provide your config.yaml?

**Comment by KubraE** [comment]
Hi,
Yes I ran it. This is the response from terminal:
```
(vame) [eryilmaz@scc-q28 VAME]$ python3
Python 3.7.7 (default, May 21 2020, 14:57:43) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vame
>>> config='/projectnb/dnn-motion/kubra/VAME/vame_trial_3-Dec2-2020/config.yaml'
>>> vame.create_trainset(config)
Creating training dataset.
/projectnb2/dnn-motion/kubra/VAME/vame_trial_3-Dec2-2020/data/Rec-000026/Rec-000026-PE-seq.npy
Lenght of train data: 160
Lenght of test data: 40
```
This is my data folder inside my project folder with sizes.
<img width="462" alt="Screen Shot 2020-12-03 at 11 34 41 AM" src="https://user-images.githubusercontent.com/34382537/101058802-8be0e580-355b-11eb-82e0-9cd526d5f6c4.png">

This is the content of my config.yaml file:
```
# Project name
Project: vame_trial_3

# Project path and videos
project_path: /projectnb2/dnn-motion/kubra/VAME/vame_trial_3-Dec2-2020/
video_sets:
- Rec-000026

# Data
all_data: yes

# Creation of train set:
savgol_filter: true
savgol_length: 5
savgol_order: 2
test_fraction: 0.2

# RNN model general hyperparameter:
num_features: 12
batch_size: 256
max_epochs: 500
model_snapshot: 50
model_convergence: 50
transition_function: GRU
beta: 1
zdims: 30
learning_rate: 0.0005
time_window: 30
prediction_decoder: 1
prediction_steps: 15

# Segmentation:
load_data: -PE-seq-clean
snapshot: no
snapshot_epoch: 50
median_filter: 5

# Video writer:
lenght_of_motif_video: 1000
# ONLY CHANGE ANYTHING BELOW IF YOU ARE FAMILIAR WITH RNN MODELS
# RNN encoder hyperparamter:
hidden_size_layer_1: 256
hidden_size_layer_2: 256
dropout_encoder: 0

# RNN reconstruction hyperparameter:
hidden_size_rec: 256
dropout_rec: 0

# RNN prediction hyperparamter:
hidden_size_pred: 256
dropout_pred: 0

# RNN loss hyperparameter:
mse_reconstruction_reduction: sum
mse_prediction_reduction: sum
kmeans_loss: 30
kmeans_lambda: 0.1
anneal_function: linear
kl_start: 3
annealtime: 8
scheduler: 1
```

**Comment by KLuxem** [comment]
Thank you! 
I think I figured out your problem. As you are only using 160 training data points and 40 test data points, your batch size is too big with 256, see config.yaml. It needs to be lower than 160. 

However, I would suggest to use far more datapoints. If you just want to try things out, it would be good to have at least 5000 - 10000 training samples as this is a generative model which needs quite a lot of data to learn. 

I hope this will help you on your journey with VAME. 

Cheers,
Kevin
