### ISSUE TITLE
Egocentric Coordinates - ValueError: array of sample points is empty

### ISSUE THREAD

**Issue by Virginia9733** [LINCellularNeuroscience/VAME#48]
Hi,

I am running VAME on colab. I could go over the pipeline with de example video and .csv. However, when I try to use VAME to analyze my own DLC video with its .csv, I encountered with this error message:

>>> vame.egocentric_alignment(config, pose_ref_index=[0,6]) # cuz I have labeled 7 body parts

Aligning data Trial_2_2739DLC_resnet50_EPMMay11shuffle1_10000_labeled, Pose confidence value: 0.99
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/envs/VAME/lib/python3.7/site-packages/vame-1.0-py3.7.egg/vame/util/align_egocentrical.py", line 314, in egocentric_alignment
  File "/usr/local/envs/VAME/lib/python3.7/site-packages/vame-1.0-py3.7.egg/vame/util/align_egocentrical.py", line 290, in alignment
  File "/usr/local/envs/VAME/lib/python3.7/site-packages/vame-1.0-py3.7.egg/vame/util/align_egocentrical.py", line 155, in align_mouse
  File "/usr/local/envs/VAME/lib/python3.7/site-packages/vame-1.0-py3.7.egg/vame/util/align_egocentrical.py", line 87, in interpol
  File "<__array_function__ internals>", line 6, in interp
  File "/usr/local/envs/VAME/lib/python3.7/site-packages/numpy/lib/function_base.py", line 1428, in interp
    return interp_func(x, xp, fp, left, right)
ValueError: array of sample points is empty

I guess it is because I only trained the video with 10000 times, therefore the pose-confidence / likelihood is generally about 0.5. 
It seems that the pose confidence threshold is set to 0.99, therefore, in my .csv there is no sample point that could meet this criterion.
Is it possible to change the Pose confidence value to 0.5, cuz I don't have a GPU and it is super slow to train a large DLC training model on colab. I just want to play with my own behavioral video.

Many thanks!

**Comment by pavolbauer** [comment]
Hi,
This particular setting is not set via the config.yaml so you are free to change it diretly in the source code (and reinstall VAME afterwards).
Hope this helps,
Pavol
